spring:
  application:
    name: config-server
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    baseUrl: ${vcap.services.zipkin-server.credentials.uri:http://localhost:9411}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ibm-cloud-architecture/refarch-cloudnative-spring-config

server:
  port: ${vcap.application.port:8888}

management:
  context-path: /admin

eureka:
  client:
    serviceUrl:
       defaultZone: ${vcap.services.eureka-service-discovery.credentials.uri:http://localhost:8761/eureka/}
  instance:
    hostname: ${vcap.application.uris[0]:localhost}
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
    preferIpAddress: true
    
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

---
spring:
  profiles: cloud
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: false
